# Systems of Linear Equations

In [1]:
import numpy as np
import scipy.linalg as la
import matplotlib.pyplot as plt

## Terminology

A **system of linear equations** is a collection of equations of the form

$$
\begin{array}{ccccccccc}
a_{0,0}x_0 & + & a_{0,1}x_1 & + & \cdots & + & a_{0,n-1} x_{n-1} & = & b_0 \\
a_{1,0}x_0 & + & a_{1,1}x_1 & + & \cdots & + & a_{1,n-1} x_{n-1} & = & b_1 \\
\vdots & & & & & & & & \vdots & \\
a_{m-1,0}x_0 & + & a_{m-1,1}x_1 & + & \cdots & + & a_{m-1,n-1} x_{n-1} & = & b_{m-1}
\end{array}
$$

where the numbers $a_{i,j}$ and $b_i$ are known coefficients, and $x_j$ are the variables. We can write the equation is matrix form as

$$
A \mathbf{x} = \mathbf{b}
$$

where

$$
A = \begin{bmatrix}
a_{0,0} & a_{0,1} & \cdots & a_{0,n-1} \\
a_{1,0} & a_{1,1} & \cdots & a_{1,n-1} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m-1,0} & a_{m-1,1} & \cdots & a_{m-1,n-1} \\
\end{bmatrix}
\hspace{20mm}
\mathbf{b} = \begin{bmatrix} b_0 \\ b_1 \\ \vdots \\ b_{m-1} \end{bmatrix}
\hspace{20mm}
\mathbf{x} = \begin{bmatrix} x_0 \\ x_1 \\ \vdots \\ x_{n-1} \end{bmatrix}
$$

Combine the matrix $A$ and the vector $\mathbf{b}$ to form the **augmented matrix**

$$
[ A \ | \ \mathbf{b} ] = \begin{bmatrix}
a_{0,0} & a_{0,1} & \cdots & a_{0,n-1} & b_0 \\
a_{1,0} & a_{1,1} & \cdots & a_{1,n-1} & b_1 \\
\vdots & \vdots & \ddots & \vdots & \vdots \\
a_{m-1,0} & a_{m-1,1} & \cdots & a_{m-1,n-1} & b_{m-1} \\
\end{bmatrix}
$$

## Elementary Row Operations

There are three types of row operations:

1. Add a multiple of one row to another
2. Multiply a row by a scalar
3. Switch rows

Write a function called `add_row` which takes `A`, `c`, `i` and `j` and returns the matrix $B$ obtained from $A$ by adding $c$ times row $i$ to row $j$ in $A$.

In [62]:
def add_row(A,c,i,j):
    B = A.astype(np.float64).copy() # Create a copy of the input matrix
    B[j,:] = c*A[i,:] + A[j,:]
    return B

In [63]:
A = np.array([[1,2,3],[-2,2,2]])
print(A)

[[ 1  2  3]
 [-2  2  2]]


In [64]:
A1 = add_row(A,2,0,1)
print(A1)

[[1. 2. 3.]
 [0. 6. 8.]]


Write a function called `scale_row` which takes `A`, `c` and `i` and returns the matrix $B$ obtained from $A$ by multiplying $c$ times row $i$.

In [65]:
def scale_row(A,c,i):
    B = A.astype(np.float64).copy() # Create a copy of the input matrix
    B[i,:] = c*A[i,:]
    return B

In [66]:
A2 = scale_row(A1,1/6,1)
print(A2)

[[1.         2.         3.        ]
 [0.         1.         1.33333333]]


Write a function called `switch_rows` which takes `A`, `i` and `j` and returns the matrix $B$ obtained from $A$ by switching rows `i` and `j`.

In [67]:
def switch_rows(A,i,j):
    B = A.astype(np.float64).copy() # Create a copy of the input matrix
    B[i,:] = A[j,:]
    B[j,:] = A[i,:]
    return B

In [68]:
A = np.array([[0,-1],[1,0]])
print(A)

[[ 0 -1]
 [ 1  0]]


In [69]:
switch_rows(A,0,1)

array([[ 1.,  0.],
       [ 0., -1.]])

## Row Echelon Form

A **pivot** is the first nonzero entry of a row of a matrix. A matrix is in **row echelon form** if:

1. All zero rows are at the bottom.
2. Each pivot is to the right of the pivot in each row above.
3. All entries are zero below each pivot.

A matrix is in **reduced row echelon form** if it is in row echelon form and:

4. Each pivot is equal to 1.
5. Each pivot is the only nonzero entry in its column.

Apply elementary row operations to transform the following matrix into row echelon form:

$$
M = \left[ \begin{array}{rrrr} -2 & 1 & 0 & 1 \\ 1 & -2 & 1 & 1 \\ 0 & 1 & -2 & 1 \end{array} \right]
$$

In [70]:
M = np.array([[-2,1,0,1],[1,-2,1,1],[0,1,-2,1]])
print(M)

[[-2  1  0  1]
 [ 1 -2  1  1]
 [ 0  1 -2  1]]


In [71]:
M1 = add_row(M,1/2,0,1)
print(M1)

[[-2.   1.   0.   1. ]
 [ 0.  -1.5  1.   1.5]
 [ 0.   1.  -2.   1. ]]


In [72]:
M2 = add_row(M1,2/3,1,2)
print(M2)

[[-2.          1.          0.          1.        ]
 [ 0.         -1.5         1.          1.5       ]
 [ 0.          0.         -1.33333333  2.        ]]


Success! Now let's take it a few steps farther and compute the reduced row echelon form:

In [73]:
M3 = scale_row(M2,-1/2,0)
print(M3)

[[ 1.         -0.5        -0.         -0.5       ]
 [ 0.         -1.5         1.          1.5       ]
 [ 0.          0.         -1.33333333  2.        ]]


In [75]:
M4 = scale_row(M3,-2/3,1)
print(M4)

[[ 1.         -0.5        -0.         -0.5       ]
 [-0.          1.         -0.66666667 -1.        ]
 [ 0.          0.         -1.33333333  2.        ]]


In [76]:
M5 = add_row(M4,1/2,1,0)
print(M5)

[[ 1.          0.         -0.33333333 -1.        ]
 [-0.          1.         -0.66666667 -1.        ]
 [ 0.          0.         -1.33333333  2.        ]]


In [77]:
M6 = scale_row(M5,-3/4,2)
print(M6)

[[ 1.          0.         -0.33333333 -1.        ]
 [-0.          1.         -0.66666667 -1.        ]
 [-0.         -0.          1.         -1.5       ]]


In [78]:
M7 = add_row(M6,2/3,2,1)
print(M7)

[[ 1.          0.         -0.33333333 -1.        ]
 [-0.          1.          0.         -2.        ]
 [-0.         -0.          1.         -1.5       ]]


In [79]:
M8 = add_row(M7,1/3,2,0)
print(M8)

[[ 1.   0.   0.  -1.5]
 [-0.   1.   0.  -2. ]
 [-0.  -0.   1.  -1.5]]


Success! In fact, we have cmputed the solution $\mathbf{x}$ of the system $A \mathbf{x} = \mathbf{b}$ where

$$
A = \left[ \begin{array}{rrrr} -2 & 1 & 0 \\ 1 & -2 & 1 \\ 0 & 1 & -2 \end{array} \right]
\hspace{10mm}
\mathbf{b} = \begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix}
\hspace{10mm}
\mathbf{x} = \begin{bmatrix} -1.5 \\ -2 \\ -1.5 \end{bmatrix}
$$

## Computing Solutions with SciPy

The function `scipy.linalg.solve` computes the unique solution of the system $A \mathbf{x} = \mathbf{b}$ for a nonsingular matrix $A$. See the [SciPy documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve.html) for more information. For example, let's compute the solution of the example from the previous section.

In [80]:
A = np.array([[-2,1,0],[1,-2,1],[0,1,-2]])
print(A)

[[-2  1  0]
 [ 1 -2  1]
 [ 0  1 -2]]


In [81]:
b = np.array([1,1,1])
print(b)

[1 1 1]


In [84]:
x = la.solve(A,b)
print(x)

[-1.5 -2.  -1.5]


:::{seealso}
Check out [Mathematical Python > Linear Algebra](https://patrickwalls.github.io/mathematicalpython/linear-algebra/solving-linear-systems/) for more about solving linear systems with Python.
:::